language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "python setup.py develop"
  - "pip install flake8"
# command to run tests
script: django-admin test working_waterfronts --settings="working_waterfronts.settings"
addons:
  postgresql: "9.3"
before_script:
  - flake8 working_waterfronts/
  - psql -c 'create database working_waterfronts;' -U postgres
  - psql -U postgres -c "create extension postgis;" working_waterfronts
